
package Ejer2;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;


public class Principal extends javax.swing.JFrame {
    
    private JLabel [] Botones;
    private Color [] colores;
    JLabel[] imagen;
    private JLabel[] contenedoresImagen;
    void LeerArchivo() throws IOException{
        String Lectura = NewClass.ReadTextFile("src/Ejer2/BaseDeDatos.json");
        System.out.println(Lectura);
        
    
}
    
    

    
    public Principal() {
        initComponents();
        
        Botones = new JLabel []{Btn1,Btn2,Btn3};
        colores = new Color []{Color.green,Color.red,Color.blue};
        for(int i=0; i<Botones.length; i++){
            final int index = i;
            final JPanel panel = content;
            Botones [i].addMouseListener(new MouseAdapter(){
                @Override
                public void mouseClicked(MouseEvent e){
                    vista2 panelcolores = new vista2 (colores[index]);
                    NewClass.PanelInPanel(panel, panelcolores);
                    
                }
                
            });
            
        }
        
        imagen = new JLabel[]{Imagen1,Imagen2,Imagen3,Imagen4};
        for(int i=0; i<imagen.length; i++){
            NewClass.escalarImagen(imagen[i], false, "src/imagenes/HomeButton0.png");
        }
        
        contenedoresImagen = new JLabel[]{Imagen1,Imagen2,Imagen3,Imagen4};
        for(int i=0; i<contenedoresImagen.length; i++){
            final int index = i;
            contenedoresImagen[i].addMouseListener(new MouseAdapter(){
                @Override
                public void mouseClicked(MouseEvent e){
                    NewClass.escalarImagen(imagen[index], true, "src/imagenes/HomeButton0.png", new Dimension (400,400));
                    System.out.println("Click");
                    
                    
                    
                    
                }
                
                
            });
            
        }
        
            
        
        
        NewClass.CreateStringList("src/imagenes","Embarque", ".png", 3);
        
        System.out.println("Inicio de la prueba"); 
        Runnable myTask = () -> {
            try {
                System.out.println("Tarea ejecutada después de esperar");
                Thread.sleep(1000);
                
            } 
            catch (InterruptedException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        };
        // Llamar a la función asyncExecute de la clase Utility
        NewClass.Async(myTask, 5); // Espera(5 segundos)

        System.out.println("Final de la prueba (la tarea se ejecutará asíncronamente)");
        
        
        
        
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        bg = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        Btn1 = new javax.swing.JLabel();
        Btn2 = new javax.swing.JLabel();
        Btn3 = new javax.swing.JLabel();
        Btn4 = new javax.swing.JLabel();
        Imagen1 = new javax.swing.JLabel();
        Imagen2 = new javax.swing.JLabel();
        Imagen3 = new javax.swing.JLabel();
        Imagen4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        contador1 = new javax.swing.JLabel();
        predeterminado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 182, Short.MAX_VALUE)
        );

        bg.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 116, 472, 184));

        Btn1.setForeground(new java.awt.Color(0, 204, 51));
        Btn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Btn1.setText("Boton1");
        Btn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Btn1.setEnabled(false);
        Btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn1MouseClicked(evt);
            }
        });
        bg.add(Btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 84, 72));

        Btn2.setForeground(new java.awt.Color(255, 0, 51));
        Btn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Btn2.setText("Boton2");
        Btn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bg.add(Btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 20, 84, 72));

        Btn3.setForeground(new java.awt.Color(0, 51, 255));
        Btn3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Btn3.setText("Boton3");
        Btn3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bg.add(Btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 20, 84, 72));

        Btn4.setForeground(new java.awt.Color(0, 0, 0));
        Btn4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Btn4.setText("BACK");
        Btn4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn4MouseClicked(evt);
            }
        });
        bg.add(Btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 24, 84, 72));

        Imagen1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Imagen1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bg.add(Imagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 392, 136, 140));

        Imagen2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Imagen2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bg.add(Imagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 332, 172, 200));

        Imagen3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Imagen3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bg.add(Imagen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 376, 296, 148));

        Imagen4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Imagen4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bg.add(Imagen4, new org.netbeans.lib.awtextra.AbsoluteConstraints(736, 12, 200, 372));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Leer archivo");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 68, 68));

        contador1.setForeground(new java.awt.Color(0, 0, 0));
        contador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contador1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        contador1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contador1MouseClicked(evt);
            }
        });
        bg.add(contador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 168, 92, 76));

        predeterminado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        predeterminado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        predeterminado.setMaximumSize(new java.awt.Dimension(400, 400));
        predeterminado.setMinimumSize(new java.awt.Dimension(400, 400));
        predeterminado.setPreferredSize(new java.awt.Dimension(400, 400));
        predeterminado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                predeterminadoMouseClicked(evt);
            }
        });
        bg.add(predeterminado, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 396, 244, 144));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
        );

        pack();
    }//GEN-END:initComponents

    private void Btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn1MouseClicked

    private void Btn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn4MouseClicked
        NewClass.borrarContenidoPanel(content);
    }//GEN-LAST:event_Btn4MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        try {
            LeerArchivo();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void contador1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contador1MouseClicked
        
       AnimacionCuentaAtras();
       
    }//GEN-LAST:event_contador1MouseClicked

    private void predeterminadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_predeterminadoMouseClicked
       String[] Rutas = new String[11];
       NewClass.CreateStringList("src/imagenes/", "Foto", "png", 11).toArray(Rutas);
       NewClass.escalarImagenesSecuencialmenteMayorMenor(predeterminado, true, Rutas, 0, 1000);
       
      


       
       

      
    }//GEN-LAST:event_predeterminadoMouseClicked
    private void AnimacionCuentaAtras(){
        String[] Rutas = new String[11]; 
        NewClass.CreateStringList("src/imagenes/", "Foto", "png", 11).toArray(Rutas);
        NewClass.escalarImagen(contador1, rootPaneCheckingEnabled, Rutas[10]);
        NewClass.Async(()->{
             try {
                
               NewClass.escalarImagen(contador1, rootPaneCheckingEnabled, Rutas[9]);
               Thread.sleep(1000);
               NewClass.escalarImagen(contador1, rootPaneCheckingEnabled, Rutas[8]);
               Thread.sleep(1000);
               NewClass.escalarImagen(contador1, rootPaneCheckingEnabled, Rutas[7]);
               Thread.sleep(1000);
               NewClass.escalarImagen(contador1, rootPaneCheckingEnabled, Rutas[6]);
               Thread.sleep(1000);
               NewClass.escalarImagen(contador1, rootPaneCheckingEnabled, Rutas[5]);
               Thread.sleep(1000);
               NewClass.escalarImagen(contador1, rootPaneCheckingEnabled, Rutas[4]);
               Thread.sleep(1000);
               NewClass.escalarImagen(contador1, rootPaneCheckingEnabled, Rutas[3]);
               Thread.sleep(1000);
               NewClass.escalarImagen(contador1, rootPaneCheckingEnabled, Rutas[2]);
               Thread.sleep(1000);
               NewClass.escalarImagen(contador1, rootPaneCheckingEnabled, Rutas[1]);
               Thread.sleep(1000);
               NewClass.escalarImagen(contador1, rootPaneCheckingEnabled, Rutas[0]);
               Thread.sleep(1000);
               
           } catch (InterruptedException ex) {
               Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
           }
         }, 1);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
                 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Btn1;
    private javax.swing.JLabel Btn2;
    private javax.swing.JLabel Btn3;
    private javax.swing.JLabel Btn4;
    private javax.swing.JLabel Imagen1;
    private javax.swing.JLabel Imagen2;
    private javax.swing.JLabel Imagen3;
    private javax.swing.JLabel Imagen4;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel contador1;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel predeterminado;
    // End of variables declaration//GEN-END:variables
}
